name: Feature Request
description: Suggest a new feature or improvement
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: dropdown
    id: component
    attributes:
      label: Component
      options:
        - Node Core
        - Smart Contracts
        - Explorer
        - Website
        - DAO Governance
        - Forum
        - DevOps / Infrastructure
        - Documentation
    validations:
      required: true
  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this solve?
      placeholder: I want to be able to...
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How should this work?
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: What other approaches did you consider?
  - type: dropdown
    id: priority
    attributes:
      label: Priority
      options:
        - Critical (blocks testnet launch)
        - High (important for launch)
        - Medium (nice to have)
        - Low (future improvement)
